### ISSUE TITLE
Chamber "show more" need to change as "show less"

### ISSUE THREAD

**Issue by ShekharUllah06** [ShekharUllah06/appointment-manager#11]
When clicked on the show more option at chamber page the information shows but at the last it is again showing "show more". Need to change this as show less. For more details please look at the image.
 
![chamber details view](https://cloud.githubusercontent.com/assets/20273137/24639075/0b8f4820-190f-11e7-8cfc-59c3e55f07c6.png)

**Comment by zaki-hashem-chow** [comment]
Overlapping part of the Issue solved. Button part still remains.

**Comment by zaki-hashem-chow** [comment]
Done, but removed the button arrow for now.
