### ISSUE TITLE
Change Personal Info Page Button Text

### ISSUE THREAD

**Issue by ShekharUllah06** [ShekharUllah06/appointment-manager#12]
Please change personal info page button change as "Edit". Please see the image for details.

![personal info](https://cloud.githubusercontent.com/assets/20273137/24639207/f0bef972-190f-11e7-9d94-73a902601baa.png)

**Comment by zaki-hashem-chow** [comment]
Issue solved. Update coming soon.

**Comment by zaki-hashem-chow** [comment]
Done.
